# Generated by Django 4.1.3 on 2022-12-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_cam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(max_length=20)),
                ('cam_models', models.CharField(max_length=30)),
                ('formfactor', models.CharField(max_length=20)),
                ('resolution', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('opticalzoom', models.CharField(max_length=10)),
            ],
        ),
    ]
